/* eslint-disable */
// @ts-nocheck
// This file was generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as ClassmatesRouteImport } from './routes/classmates'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AboutRoute = AboutRouteImport.update({ id: '/about', path: '/about', getParentRoute: () => rootRouteImport } as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({ id: '/forgot-password', path: '/forgot-password', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({ id: '/reset-password', path: '/reset-password', getParentRoute: () => rootRouteImport } as any)
const SignupRoute = SignupRouteImport.update({ id: '/signup', path: '/signup', getParentRoute: () => rootRouteImport } as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({ id: '/verify-email', path: '/verify-email', getParentRoute: () => rootRouteImport } as any)
const ChatsRoute = ChatsRouteImport.update({ id: '/chats', path: '/chats', getParentRoute: () => rootRouteImport } as any)
const ClassmatesRoute = ClassmatesRouteImport.update({ id: '/classmates', path: '/classmates', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute; '/about': typeof AboutRoute; '/forgot-password': typeof ForgotPasswordRoute; '/login': typeof LoginRoute; '/reset-password': typeof ResetPasswordRoute; '/signup': typeof SignupRoute; '/verify-email': typeof VerifyEmailRoute; '/chats': typeof ChatsRoute; '/classmates': typeof ClassmatesRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport; '/': typeof IndexRoute; '/about': typeof AboutRoute; '/forgot-password': typeof ForgotPasswordRoute; '/login': typeof LoginRoute; '/reset-password': typeof ResetPasswordRoute; '/signup': typeof SignupRoute; '/verify-email': typeof VerifyEmailRoute; '/chats': typeof ChatsRoute; '/classmates': typeof ClassmatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/forgot-password' | '/login' | '/reset-password' | '/signup' | '/verify-email' | '/chats' | '/classmates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/forgot-password' | '/login' | '/reset-password' | '/signup' | '/verify-email' | '/chats' | '/classmates'
  id: '__root__' | '/' | '/about' | '/forgot-password' | '/login' | '/reset-password' | '/signup' | '/verify-email' | '/chats' | '/classmates'
  fileRoutesById: FileRoutesById
}
declare module '@tanstack/react-router' { interface FileRoutesByPath {
  '/': { id:'/'; path:'/'; fullPath:'/'; preLoaderRoute:typeof IndexRouteImport; parentRoute:typeof rootRouteImport }
  '/about': { id:'/about'; path:'/about'; fullPath:'/about'; preLoaderRoute:typeof AboutRouteImport; parentRoute:typeof rootRouteImport }
  '/forgot-password': { id:'/forgot-password'; path:'/forgot-password'; fullPath:'/forgot-password'; preLoaderRoute:typeof ForgotPasswordRouteImport; parentRoute:typeof rootRouteImport }
  '/login': { id:'/login'; path:'/login'; fullPath:'/login'; preLoaderRoute:typeof LoginRouteImport; parentRoute:typeof rootRouteImport }
  '/reset-password': { id:'/reset-password'; path:'/reset-password'; fullPath:'/reset-password'; preLoaderRoute:typeof ResetPasswordRouteImport; parentRoute:typeof rootRouteImport }
  '/signup': { id:'/signup'; path:'/signup'; fullPath:'/signup'; preLoaderRoute:typeof SignupRouteImport; parentRoute:typeof rootRouteImport }
  '/verify-email': { id:'/verify-email'; path:'/verify-email'; fullPath:'/verify-email'; preLoaderRoute:typeof VerifyEmailRouteImport; parentRoute:typeof rootRouteImport }
  '/chats': { id:'/chats'; path:'/chats'; fullPath:'/chats'; preLoaderRoute:typeof ChatsRouteImport; parentRoute:typeof rootRouteImport }
  '/classmates': { id:'/classmates'; path:'/classmates'; fullPath:'/classmates'; preLoaderRoute:typeof ClassmatesRouteImport; parentRoute:typeof rootRouteImport }
} }
const rootRouteChildren = { IndexRoute, AboutRoute, ForgotPasswordRoute, LoginRoute, ResetPasswordRoute, SignupRoute, VerifyEmailRoute, ChatsRoute, ClassmatesRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' { interface Register { ssr:true; router:Awaited<ReturnType<typeof getRouter>>; config:Awaited<ReturnType<typeof startInstance.getOptions>> } }
